server:
  port: 8080

spring:
  application:
    name: OPTION-CHAIN
  jackson:
    deserialization:
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
  task:
    scheduling:
      pool:
        size: 2

application:
  couchbase:
    scope: nse
    username: Administrator
    password: Administrator
    host: 172.17.0.2
    bucket: bucket-0
  webClient:
    nse:
      baseUrl: https://www.nseindia.com
      apiVersion: /api
